name: beaver_cli
version: 0.1.0
description: Command line interface for the Beaver.

author: Fluidic Team <dev@fluidic.io>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  args: '>=0.13.5 <0.14.0'
  ini: '>=1.1.0 <1.2.0'
  yaml: '>=2.1.10 <2.2.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
