name: beaver_config_store
description: Store for beaver configuration.
version: 0.1.0
author: Fluidic Team <dev@fluidic.io>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  beaver_task:
    path: ../beaver_task
  path: '>=1.3.9 <1.4.0'
  quiver_collection: '>=1.0.0 <1.1.0'
  uuid: '>=0.5.3 <0.6.0'
  yaml: '>=2.1.10 <2.2.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
