name: pub_wrapper
description: A wrapper around the Pub command line
version: 0.1.0
author: Fluidic Team <dev@fluidic.io>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  which: '>=0.1.3 <0.2.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
