name: beaver_dart_task
description: Collection of Beaver Dart tasks
version: 0.1.0
author: Fluidic Team <dev@fluidic.io>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  beaver_task:
    path: ../beaver_task
  command_wrapper : ^0.2.0

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
