name: beaver_task
description: Task classes of beaver.
version: 0.1.0
author: Fluidic Team <dev@fluidic.io>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  archive: '>=1.0.24 <1.1.0'
  args: '>=0.13.5 <0.14.0'
  beaver_gcloud:
    path: ../beaver_gcloud
  file_helper:
    path: ../file_helper
  gcloud: '>=0.3.0 <0.4.0'
  googleapis: any
  googleapis_auth: any
  git: '>=0.4.4 <0.5.0'
  logging: '>=0.11.3+1 <0.12.0'
  path: '>=1.3.9 <1.4.0'
  quiver_collection: '>=1.0.0 <1.1.0'
  quiver_iterables: '>=1.0.0 <1.1.0'
  quiver_strings: '>=1.0.0 <1.1.0'
  uuid: '>=0.5.3 <0.6.0'
  yaml: '>=2.1.10 <2.2.0'

dev_dependencies:
  beaver_dart_task:
    path: ../beaver_dart_task
  beaver_gcloud_task:
    path: ../beaver_gcloud_task
  shelf: '>=0.6.5+3 <0.7.0'
  shelf_route: '>=0.14.2 <0.15.0'
  test: '>=0.12.0 <0.13.0'
