name: beaver_core
description: Core classes of beaver.
version: 0.1.0
author: Fluidic Team <dev@fluidic.io>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  gcloud: '>=0.2.0 < 0.3.0'
  googleapis_auth: '>=0.2.3 < 0.3.0'
  quiver_collection: '>=1.0.0 <1.1.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
