name: beaver_trigger_handler
description: Handler for trigger.
version: 0.1.0
author: Fluidic Team <dev@fluidic.io>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  beaver_store:
    path: ../beaver_store
  beaver_task:
    path: ../beaver_task
  logging: '>=0.11.3+1  <0.12.0'
  yaml: '>=2.1.10 <2.2.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
