name: beaver_api
description: Rest API for beaver.
version: 0.0.1
author: Fluidic Team <dev@fluidic.io>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  beaver_store:
    path: ../beaver_store

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
  shelf: '>=0.6.5+3 <0.7.0'
  shelf_route: '>=0.14.2 <0.15.0'
