name: beaver_gcloud_task
description: Collection of Beaver Google Cloud tasks
version: 0.1.0
author: Fluidic Team <dev@fluidic.io>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  beaver_task:
    path: ../beaver_task
  gcloud: '>=0.3.0 <0.4.0'
  googleapis_auth: any

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
